// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ91xxMj7er7jIQTkL20jc7XDN15XJgZE',
    appId: '1:709386959794:android:878b7ec3e40eff1ac202ab',
    messagingSenderId: '709386959794',
    projectId: 'mynotes-43b4f',
    storageBucket: 'mynotes-43b4f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKffQnVuP_l_A0Sa9NiLSQttbGw2xVnB0',
    appId: '1:709386959794:ios:7dfb86bab2cb332bc202ab',
    messagingSenderId: '709386959794',
    projectId: 'mynotes-43b4f',
    storageBucket: 'mynotes-43b4f.firebasestorage.app',
    iosClientId: '709386959794-sa4l5sh3g21o0mq9rs3qat6rg0s90gh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.makenotesNew',
  );

}